apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eraser
  namespace: eraser
spec:
  targetNamespace: eraser-system
  releaseName: eraser
  chart:
    spec:
      chart: eraser
      sourceRef:
        kind: HelmRepository
        name: eraser
        namespace: eraser
      version: "1.0"
  interval: 5m0s
  install:
    remediation:
      retries: 3
