apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eraser1
  namespace: eraser
spec:
  targetNamespace: eraser-system
  releaseName: eraser2
  chart: eraser
    spec:
      chart: 
      sourceRef:
        kind: HelmRepository
        name: eraser3
        namespace: eraser
      version: "1.0"
  interval: 1m0s
  install:
    remediation:
      retries: 3
