apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-eraser-release
  namespace: eraser
spec:
  targetNamespace: eraser-system
  releaseName: eraser-helm
  chart:
    spec:
      chart: eraser
      sourceRef:
        kind: HelmRepository
        name: eraser3
        namespace: eraser
      version: "1.x"
  interval: 1m0s
  install:
    createNamespace: true  
    remediation:
      retries: 3
